In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('cclass.csv')

In [3]:
df.head()

      model  year  price transmission  mileage fuelType  engineSize
0   C Class  2020  30495    Automatic     1200   Diesel         2.0
1   C Class  2020  29989    Automatic     1000   Petrol         1.5
2   C Class  2020  37899    Automatic      500   Diesel         2.0
3   C Class  2019  30399    Automatic     5000   Diesel         2.0
4   C Class  2019  29899    Automatic     4500   Diesel         2.0

In [4]:
df.shape

(3899, 7)

In [5]:
df.isnull().any()

model           False
year            False
price           False
transmission    False
mileage         False
fuelType        False
engineSize      False
dtype: bool

In [6]:
df['fuelType'].unique()

array(['Diesel', 'Petrol', 'Hybrid', 'Other'], dtype=object)

In [7]:
df['transmission'].unique()

array(['Automatic', 'Semi-Auto', 'Manual', 'Other'], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder 
  
le = LabelEncoder() 
  
df['fuelType']= le.fit_transform(df['fuelType']) 
df['transmission']= le.fit_transform(df['transmission'])

In [9]:
df['fuelType']

0       0
1       3
2       0
3       0
4       0
       ..
3894    0
3895    0
3896    0
3897    0
3898    0
Name: fuelType, Length: 3899, dtype: int32

In [10]:
df['transmission']

0       0
1       0
2       0
3       0
4       0
       ..
3894    1
3895    0
3896    1
3897    0
3898    0
Name: transmission, Length: 3899, dtype: int32

In [11]:
from sklearn import preprocessing, svm 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression

In [12]:
reg = LinearRegression()

In [13]:
df

         model  year  price  transmission  mileage  fuelType  engineSize
0      C Class  2020  30495             0     1200         0         2.0
1      C Class  2020  29989             0     1000         3         1.5
2      C Class  2020  37899             0      500         0         2.0
3      C Class  2019  30399             0     5000         0         2.0
4      C Class  2019  29899             0     4500         0         2.0
...        ...   ...    ...           ...      ...       ...         ...
3894   C Class  2017  14700             1    31357         0         1.6
3895   C Class  2018  18500             0    28248         0         2.1
3896   C Class  2014  11900             1    48055         0         2.1
3897   C Class  2014  11300             0    49865         0         2.1
3898   C Class  2014  14800             0    55445         0         2.1

[3899 rows x 7 columns]

In [14]:
x = df[['year','transmission','mileage','fuelType','engineSize']]
y = df['price']

In [15]:
x_train,x_test,y_train,y_test = train_test_split(df[['year','transmission','mileage','fuelType','engineSize']],df['price'],test_size = 0.2)

In [16]:
x_train

      year  transmission  mileage  fuelType  engineSize
670   2013             3    42477         3         1.6
466   2015             3    39877         0         2.1
2561  2019             3    14354         3         1.5
971   2016             3    43559         0         2.1
3009  2015             1   150000         0         2.1
...    ...           ...      ...       ...         ...
1320  2016             3    44335         0         2.1
309   2016             3    28535         0         2.1
2995  2019             0     4443         0         2.0
387   2019             3     3539         0         1.6
3757  2019             0     7712         0         1.6

[3119 rows x 5 columns]

In [17]:
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
reg.predict(x_test)

array([ 12549.76260182,  30840.2872786 ,  27430.15901419,  22573.80253796,
        48526.28986229,  20414.7537865 ,  14539.35540905,  17727.39506054,
        21643.47895764,  26085.03627468,  17766.54847596,  26554.82091234,
        26012.20770497,  18620.84002451,  23050.53206033,  20968.8133672 ,
        19761.78628348,   9076.17804169,  39244.4131809 ,  21499.42780269,
        27811.63024513,  23571.05994029, -15179.74063062,  25676.26376281,
        25741.02625513,  23467.95903128,  24801.84181067,  22751.54104806,
        26867.68760058,  17163.66668223,  23189.26598302,  26950.23897555,
         6738.21456891,  22980.16637452,  27803.55122195,  24587.4199282 ,
        11208.385179  ,  17661.5640211 ,  11726.29165826,  26589.81029597,
        22457.89765733,  21311.65062532,  26226.09541434,  27080.73926041,
        30218.9843342 ,  24145.78123528,  27267.15916909,  16988.77074979,
        27163.35378784,  39635.20335084,  22341.07454746,   3533.25608091,
        24592.63220122,  20458.01565259,  24930.90872045,  24087.31631716,
        20506.55294416,  27679.36881716,  45383.02965524,  29889.95959959,
        24101.8878461 ,  24744.70026669,  30215.65950918,  21938.03553592,
        22708.67010244,  22571.39386265,  26697.50688636,  22821.64612023,
        28459.58293633,  20244.942197  ,  42919.19323873,  26900.00369332,
        26381.49724868,  18204.03283254,  24588.98361011,  30770.70343374,
        23550.58146279,   8906.91106717,   -565.6789382 ,  12844.14677164,
        20923.99286089,  21368.14167495,  29359.54366507,  16588.62266091,
        11566.21276376,  27638.51930686,  24589.63514424,  12714.05705894,
        17776.23906932,  28244.24890609,  10173.07395999,  24478.22280836,
        30207.38702672,  12387.19567678,  23555.86192996,  28404.52630156,
        19589.18573286,  28107.75450724,  22609.1399955 ,  20951.98703264,
        23662.77563962,  15104.16834359,  23874.75263295,  24881.39212673,
        22542.52786005,  21643.47895764,  12575.30273964,  20566.94711708,
        10792.50686463,  19030.1134578 ,  30548.13937563,  20678.42660734,
        20659.0119301 ,  28404.52630156,  23403.19653896,  27811.82770634,
        38441.26906236,  30621.63242526,  26433.93522465,  24971.46771632,
        22314.38091432,  24303.05685351,  26339.92937132,  26579.44890238,
        22555.1686619 ,  26283.62387688,  26086.59995659,  28459.58293633,
        21322.73174719,  24485.09548886,  21650.44837185,  19935.15751396,
        20428.49811586,  24683.46900445,  24779.84952834,  25854.65380704,
        24793.72888478,  25693.56098936,  22468.06054996,  28198.96928516,
        24101.84248748,  26748.58716199,  16774.46124502,  26005.94003155,
        24546.12665005,  15999.69792194,  26032.42084856,  27948.452412  ,
        25675.234254  ,   6234.70899484,  18360.5302903 ,  23747.73672968,
        27215.86607733,  28018.80847221,  24534.12443654,  16464.04933565,
        27875.6108965 ,  24840.41263104,  17792.03609599,  14550.16583387,
        19154.70783388,  33421.26784052,  29895.43248626,  25892.70340011,
        18419.04263994,  16325.63127498,  25542.82957341,  39168.90237644,
        22846.27411026,  29342.71481846,  22557.06011183,  26937.81066838,
        27566.65341303,  22635.50482084,  22622.39804004,  23873.17935615,
        26143.35058009,  30107.89576442,  22570.9357878 ,  30616.81107272,
        22630.05224004,  19640.59589398,  12925.37506732,  26707.68881439,
        26409.50027039,  32653.76232861,  20225.96024704,   4184.79020885,
        11900.74728544,  22679.92650257,  20313.82914912,  21531.87420226,
        30147.76965305,  22290.60295939,  19880.63218988,  42377.04968991,
        12642.11792927,  16674.88577945,  27562.74420826,  24825.40807999,
        17857.35202751,  25029.38709934,  30198.85025013,  17259.76492537,
        24537.84912589,  22520.50704629,  19379.00694258,  21643.47895764,
        21959.40585531,  24928.82381124,  27373.53869751,  23419.49383602,
        24263.41400734,  21643.47895764,  18272.83838163,  16206.55696682,
        27062.23569118,  17561.16565273,  28272.39518041,  19530.81084921,
        15702.8949555 ,  20401.56058521,  12065.33781758,  27201.16076289,
        27242.97125827,  29933.2177852 ,  21115.0226672 ,  26766.4391971 ,
        30183.73465836,  28303.21474563,  18741.22426525,  30356.58834202,
        24674.72550135,  23854.67578692,  55500.65241027,  26241.01354491,
        18316.22551286,  10291.61350854,  24550.80371021,  30441.54471182,
        26244.14090872,  27451.07125873,  25490.73905507,  18769.49980663,
        19011.34572974,  25944.96938296,  24694.27152518,  39244.4131809 ,
        18834.32545139,  38400.41587157,  27700.08760243,  21861.87319732,
        37121.3291133 ,  30451.96925787,  24555.49475593,  15386.21488359,
        12657.07331343,  13665.31933568,  17056.07622617,  25426.46557816,
        26799.40682397,  18539.04914484,  22268.95172046,  25466.86069409,
        12168.78576073,  27794.95097146,  27601.18472181,  50065.07812396,
        22409.42247844,  25522.43855617,  30092.19211242,  16724.91901552,
        22263.60914061,  30665.41551866,  28260.53725928,  30452.36017834,
        17390.98493851,  15025.59228799,  24655.7136506 ,  26547.52373011,
        26476.68438381,  28459.58293633,  26011.02199775,  24438.47922655,
        24850.19962852,  24918.33611274,  26494.56072672,  23742.91433736,
        26577.25168198,  27836.32538955,   5404.9520299 ,    475.87311362,
        23558.69542845,  20602.02500075,  15431.19029271,  22952.95151408,
         7780.08079194,  28111.20563716,  26459.74449649,  30349.74523271,
        17477.50763092,  25028.99617886,  28002.85751265,  27338.61646825,
        24515.6208673 ,  19510.31516091,  25279.12181009,  27210.43359832,
        15475.73521602,  19362.32870867,  30370.14025188,  11579.53292097,
        26411.84579325,  28459.71324316,  25804.09475871,  15527.37166143,
        24359.7739039 ,  20039.66358808,  27367.41427671,  22774.02097644,
        20188.8027907 ,  10271.27109789,  27661.77739571,  20222.35375755,
        23882.67144854,  48513.12887291,  22639.60644511,  14539.74632952,
        26844.49298562,  30137.67287503,  22774.80281739,  15901.74685182,
        20259.0092527 ,  26072.34230401,   1057.42639474,  30917.689533  ,
        22517.57210198,  26895.64041563,  20606.17451328,  37363.17858159,
        30120.53584795,  27606.75834412,  23119.55183133,  19138.72265271,
        20084.61989965,  25978.57559818,  26019.1977465 ,  25540.4208981 ,
        24965.25597057,  27937.99829476,  22560.70870295,  22458.02692439,
        27903.75717082,  14291.60384023,  26463.64475739,  20969.3396362 ,
        29727.6607688 ,  16588.62266091,  16459.01035132,  25892.70340011,
        29812.88111129,  19800.96579141,  23074.86618505,  -3493.65763279,
        22920.4858484 ,  28576.72877253,  24838.39087428,  29933.34809203,
        24588.46238281,  27564.89627185,  28281.90757868,  24697.9201163 ,
        21834.98714468,  21076.45184683,  48536.25633349,  22329.21662633,
        15410.48643888,  38341.97526126,  21794.63487532,  26840.97470133,
        25491.81645215,  26093.25855048,  27368.97795861,  15735.84765094,
        27329.62529729,  29684.78950174,  27476.3507829 ,  30441.414405  ,
        13276.54692058,  17474.25100006,  13722.52403211,  23568.63199887,
        17455.8145852 ,  21325.52675802,  26715.09830781,  24988.50433736,
        10453.51057921,  26851.98762906,  30451.45171105,  25094.60630529,
        27419.53700694,  20547.27582812,  24073.4406412 ,  15033.65911032,
        25033.06927171,  20440.29392431,  25294.85568432,  21474.95117029,
        38974.41743829,  27037.99862162,  -6831.40644946,  26784.16092538,
        28534.70282032,  23801.29179522,  29945.79407339,  24597.71416742,
        29162.95500835,  23438.58578693,  39762.38281262,  27547.43515722,
        14982.39861604,  27396.80046684,  28404.52630156,  25942.90477964,
        28021.68484798,  20303.79552355,  24550.41278973,  -5352.94361442,
        23383.33569288,  24613.00795428,  28532.74821794,  24767.61500188,
        26165.89366092,  27231.76487127,  26254.11138184,  24983.55267799,
        22594.45817078,  30564.36057446,  25219.14741865,  27879.71756247,
        24637.45774923,  25241.299579  ,  19077.34664134,  43391.61863393,
        17424.04962053,  21998.88882347,  27643.21067402,  19952.35801494,
        28459.58293633,  24831.62936166,  18621.08137206,  16316.21320129,
        24912.69901654,  13932.0528227 ,  25146.30590315,  22819.62836539,
        27779.29352506,  48223.78056573,  24878.39506974,   9456.38641925,
        24431.34560282,  27185.24533453,  30734.1503682 ,  16198.35371828,
        41156.07473415,  25966.19644974,  21820.95789386,  19803.41731329,
        48510.19496837,  18544.06545318,  30196.0503329 ,  19665.74511132,
        27490.23046078,  24926.86920886,  21643.47895764,  20021.48778687,
        27094.4214771 ,  27953.34091892,  24844.1051085 ,  20777.37588635,
        24289.66883173,  22238.3927689 ,  23657.1734859 ,  28110.81471668,
        25538.98752302,  53829.4673721 ,  38315.19520764,  26078.39062657,
        28318.97682982,  24973.23917266,  27753.12248045,  22979.57799284,
        26711.77748472,  24579.99243914,  24503.893253  ,  17407.60105973,
        18298.57093895,  10034.32572215,  20622.97905209,   2690.08635673,
        19255.73668557,  22820.82039293, -15752.59656819,  23392.76695121,
        13819.05721737,  31890.94448081,  21753.58822526,  24203.35150461,
        17125.28932113,  17857.35202751,  23869.55962604,  26533.9226615 ,
        15931.5834344 ,  -8581.05920686,  27920.76389108,  48536.25633349,
        13465.49685938,  22289.47304453,  26805.79185842,  22130.75933096,
        24846.33959064,  30069.65271208,  28133.81587236,  30862.37228458,
        27332.49204745,  18369.19219672,  25151.25756252,  14058.35966413,
        27857.95632259,  28284.77432884,  25020.16889598,  24634.72130589,
        19669.91997144,  26263.81723939,  17205.81789957,  15566.386665  ,
        26826.64095052,  30602.41016753,  27976.59868633,   8299.16003263,
        17897.84523837,  28197.6662169 ,   6044.07619048,  20817.72460389,
        25678.9370537 ,  26861.95410025,  27543.19818442,  29974.72218867,
        25938.11732979,  39345.92219804,  23800.00935429,  10653.08464272,
        27183.81195945,  24816.6103683 ,  25039.97553347,  27247.01076986,
        16074.92598425,  24319.91400083,  19764.98184144,  24319.44594234,
        13984.04371168,  15469.09460961,  16891.8616134 ,  25782.79159369,
        17993.4544661 ,  27299.91534105,  26411.71548643,  14987.99676785,
        24769.75747057,  16304.42451408,  12985.77028001,  25858.20566445,
        17592.56959769,  27596.82144412,  24591.63763489,  24972.32702488,
        22782.03284525,  25788.13417354,  47528.66080559,  28146.12786642,
        16317.47520768,  25022.95322758,  25026.82748987,  19579.4834893 ,
        18354.53617632,  30862.63289823,  10716.73508715,  39580.41133165,
        23714.48831857,  27743.47977535,  26738.03230912,  28231.21822353,
        18662.97197575,  28544.54298661,  20278.1250789 ,  25389.08046501,
        41652.54543044,  28024.29098449,  40608.52545303,  20226.06446135,
        28229.33077552,  27243.16871947,  12269.05452931,  25821.45881819,
        20854.40901603,  13312.38633931,  24489.05122067,  23458.13181077,
        16588.62266091,  20108.13678419,  21436.6830652 ,  30428.51402926,
        22819.95213149,  16588.62266091,  18447.88076532,  25970.62688181,
        27875.93866452,  24563.18285864,  24210.03209519,  29924.74784154,
        25517.41974242,  38589.36076868,  39178.60823398,  28179.81418179,
        18152.95610209,  24519.79068572,  25444.18730644,  16154.24181708,
        16410.75488376,  25122.66615913,  26208.37368606,  24555.08456935,
        39752.34918705,  39191.31515044,  13369.91480185,  26744.28703675,
        17729.71449089,  28570.21343125,  24581.68642788,  22728.04297289,
        27227.66220723,  10323.77180282,  26451.00499531,  23480.12041262,
        17701.67939258,  25208.562665  ,  24508.9752192 ,  25159.72750618,
        20063.90065764,  30202.82628783,  22981.46944277,  24423.49394161,
        38696.27952003,  23161.94439621,  26661.67250932,  13366.59397876,
        42041.70707522,  15563.80245954,  13319.16229424,  28586.89270493,
        17071.75752362,  30861.32982997,  51350.83809015,  28294.54734076,
        22207.67530053,  30106.65617006,  38643.56840812,  25515.59544686,
        23118.76494868,  27482.996431  ,  21140.43249819,  43681.03009356,
        24321.06659168,  20231.34997022,  27718.33055801,  27998.0361601 ,
        27129.47401318,  23028.09749058,  30419.58969123,  27783.48397081,
        18975.18712985,  25547.48703787,  24500.32076012,  26925.15291066,
        26937.07766472,  39503.593457  ,  10548.33292429,  16328.66054387,
        41494.41840775,  26599.12523304,  25798.84890443,   7419.52180554,
        24180.38929333,  20278.64630621,  22619.86800177,  32593.36542511,
        27095.1401656 ,  22431.88946103,  25586.61266681,  24944.76913223,
        30431.31762698,  25556.05771717,  17267.26060857,  30611.26934087,
        15842.42366492,  26127.51629982,  27229.02842793,  23952.53517316,
        28133.81587236,  19002.77007524,  39540.86120912,  24604.46022158,
        14862.323917  ,  23189.58974912,  23795.49618222,  24290.5039354 ,
        24991.2407807 ,  26334.73268392,  20519.1488199 ,  28574.5135565 ,
         9859.87478347,  26584.9608355 ,  25490.34949581,  48690.73707618,
        27424.61897314,  27410.74297573,  28068.66245957,  -3363.3508072 ,
        11082.6810344 ,  15357.58186769,  10942.57926584,  29899.08107738,
        26120.75329068,  48650.73288073,  20564.21571544,  13426.91995753,
        28198.96928516,   4757.32710673,  23230.0898243 ,  25774.87244852,
        23016.13105838,   9457.38921113,  22084.89132835,  27853.26527687,
        27028.35591653,  22228.11779578,  19351.2526285 ,  24720.07227665,
        30452.36017834,  14239.45224899,  28258.29247206,  21190.03225541,
        41856.93199654,  27938.48594081,  24061.42824074,  39628.49455029,
        22851.74699694,  26770.60901551,  17501.41693246,  20726.7714794 ,
        13461.91038094,  26185.30937793,  19942.31980441,  25463.37566147,
        20608.64530127,  25616.94057591,  24542.72468702,  20301.79881953,
         9787.64985962,  23246.33533093,  20215.18688215,  27501.69746144,
        14503.48778034,  17191.31203514,  26387.86933735,  19620.50847226,
        18287.16709075,  30301.59518114,  27068.49041881,  14093.04948971])

In [19]:
reg.score(x_test,y_test)

0.7655585654088617